# Generated by Django 3.2.7 on 2021-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Mng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_word', models.TextField()),
                ('the_mng', models.TextField()),
            ],
        ),
    ]
